# Answer 1:

In [1]:
import numpy as np
list_=['1','2','3','4','5']
array_list=np.array(object=list_)

In [2]:
list_

['1', '2', '3', '4', '5']

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Yes, there is a difference between the variables list_ and array_list.

In [10]:
print(array_list.dtype)
print(type(list_))

<U1
<class 'list'>


# Answer 2:

In [15]:
# code to print the data type of each element in list_
for i  in list_:
    print(type(i))

# code to print the data type of each element in array_list
for i in array_list:
    print(i.dtype)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<U1
<U1
<U1
<U1
<U1


# Answer 3:

In [16]:
array_list = np.array(object = list_, dtype = int)

Yes there will be the difference in the array_list variable because we have given the parameter that the data type would be integer type . But there will be no change in the list_ as the data present in both of them is not swallowed data.

In [20]:
# datatype of elements present in array_list
for i in array_list:
    print(i.dtype)

int64
int64
int64
int64
int64


# Answer 4:

In [21]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

(i)

In [22]:
num_array.shape

(2, 3)

(ii)

In [23]:
num_array.size

6

# Answer 5:

In [37]:
zero=np.zeros((3,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Answer 6:

In [38]:
identity=np.eye(5,5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
